# config.yml
belt_engine:
  pin_out_1: 10
  pin_out_2: 25
  pin_out_3: 9
  pin_out_4: 11
  step_sleep: 0.0025
bottle_engine:
  pin_out_1: 17
  pin_out_2: 18
  pin_out_3: 27
  pin_out_4: 22
  step_sleep: 0.001
belt_limit_sensor:
  pin_signal: 16
bottle_slot_position:
  slot_1: 0 # in step
  slot_2: 1100
  slot_3: 1980
  slot_4: 3
  slot_5: 4
  slot_6: 5
  slot_7: 6
  slot_8: 7
  slot_9: 8
  slot_10: 9
  slot_11: 10
  slot_12: 11
time_for_one_quantity: 0.18 # time in seconds for 1 cl
time_for_fill_dispensor: 0.18 # time in seconds for fill dispensor
present_position: 1700